name: "run"
inputs:
  file:
    type: TEXT
    required: true
docker_image_name: "library/node"
docker_image_tag: "20"
volume_mappings:
  - /:/buddy
execute_commands:
  - node dist/$file
shell: "BASH"
